### ISSUE TITLE
No communication on pogo pin port

### ISSUE THREAD

**Issue by pabloaul** [ddvk/remarkable2-recovery#11]
I'm having bad luck getting anything like "Freescale SemiConductor" to show up on dmesg via the pogo pins. 

I soldered the USB cable directly to the pogo pins on PCB and checked continuity with my multimeter and all seems fine.
Soldered a 10kOhm resistor on test point 3 (SBU2) and later just to make sure on test point 4 too (SBU1).

Deattaching the Pogo Vbus does show regular USB errors in the terminal and plugging in via USB-C also shows the ""cdc_ether"" device making me assume that the device just boots normally and terminal works as intended. Tested different USB ports on computer, no success. All done with both (un)plugged battery to make sure that it is shutdown.

Struggling with this since more than a day now because I forgot to note/change the ssh key and the GUI is not going beyond the splashscreen...

ReMarkable 2 device on the latest beta firmware 2.10.0.295

**Comment by pabloaul** [comment]
Maybe an easier question to ask for now would be: Is any activity in the terminal expected when SBU is not properly bridged?

**Comment by ddvk** [comment]
post photos of the setup

something is probably not connected

**Comment by jmpesp** [comment]
Note SBU2 is not symmetric in the cable:

![usb-c-24-pin-connector](https://user-images.githubusercontent.com/2858890/134940678-952878bb-7e21-4ca8-b781-79c92c758e40.png)

What worked for me was flipping the USB-C cable :)

**Comment by pabloaul** [comment]
sadly no luck
![IMG_20220105_201914](https://user-images.githubusercontent.com/35423980/148276165-5dc12983-ee36-4187-808d-ab5f8291c3bc.jpg)
This is how the setup currently looks like.
This time I'm using a proper breakout board, but the device still keeps booting into OS. When I have the main usb-c connected (with b8 still pulled down) I can observe it finding an ethernet adapter device which makes me assume that it is not going into recovery at all.

**Comment by alistair23** [comment]
Try flipping the USB-C board. It usually only works one way around

**Comment by pabloaul** [comment]
I've tried pretty much all I could do there including flipping. Starting to think this one is a lost cause...

**Comment by jmpesp** [comment]
@pabloaul your setup looks much more stable than mine! I didn't solder the micro usb connector.

Note I specifically used a [USB-C 3.1 gen 2 cable][1], so that may be something to try.

[1]: https://www.amazon.ca/gp/product/B07D7SP4T4

**Comment by jmpesp** [comment]
My setup was rm2's usbc connected to a [USB-C breakout board that includes SBU2, and I used a breadboard to attach the pull down resistor.](https://operand.ca/images/2021/09/rm2_recovery/recovery_hardware.jpg)

Your USB-C breakout board is connected directly so my cable suggestion may not be valid.

**Comment by terev** [comment]
I'm having basically the same issue as @pabloaul . I disabled the default launcher and I guess enabling the oxide launcher failed without me noticing. Then rebooted without writing down the ssh key and now It's just stuck on the splash screen. It won't even turn off when holding power. 

I'm just getting USB enumeration errors when trying to make a connection. My last ditch effort will be to find a pogo connector and learn how to solder lol. Hoping its just an unstable connection.

**Comment by rndmono** [comment]
@terev Since you are getting enumeration errors, you might want to try enforcing a USB 1.x connection, which is likely more stable and could work (it did for me). The easiest way might be to use an old USB Hub which only supports USB 1.x. Enforcing a lower speed on the host PC might be possible as well, but depends on your hardware (did not work with my PCs).

**Comment by pabloaul** [comment]
After building up motivation to look at this device again under the microscope, I've noticed that I had torn two pads which was why it wasn't able to boot into recovery.
![image](https://github.com/user-attachments/assets/b997c3ff-06d6-4a74-b408-abc591af4468)
Fixing those two spots made everything work for me and now the device starts up again after fixing my mess from 3 years ago :)

I will close this issue since it is a very specific case of me being insane to open the device to bridge the SBUS2.
