### ISSUE TITLE
USB-C Breakout Board male - Broken link

### ISSUE THREAD

**Issue by alessionossa** [ddvk/remarkable2-recovery#14]
https://github.com/ddvk/remarkable2-recovery/blob/e61ede889cf9ec210417cb17229a54547f1e6423/parts.md?plain=1#L3

It looks like link for _USB-C Breakout Board male_ is outdated.

**Comment by ddvk** [comment]
works on my machine i.e. still opens

**Comment by alessionossa** [comment]
For some obscure reason, the link 
https://www.aliexpress.com/i/4000026719770.html don’t work while I am logged in in AliExpress, while https://www.aliexpress.com/item/4000026719770.html works fine in all cases.

**Comment by ddvk** [comment]
ok, i fixed the link
