### ISSUE TITLE
Device booting from wrong partition.

### ISSUE THREAD

**Issue by hgk8769789** [ddvk/remarkable2-recovery#19]
I used the partition switcher and accidentally switched to a partition that doesn't exist, and now it's stuck on boot. I bought the recovery hardware and received it. What do I do now? How do I switch back to my original partition?
(I have my shh password, also I don't care about the files I have there, so if it is easier I can hard rest)

**Comment by Eeems** [comment]
`switch.sh` can't switch you to a partition that doesn't exist, unless you've repartitioned your device. It will only switch between the two root partitions. If you can't SSH in anymore, you'll need to go through the recovery steps and either fix any issues with the active partition, or replace it with working contents. See the readme for details.
