### ISSUE TITLE
What breakdown does this project aim to？

### ISSUE THREAD

**Issue by Lebesge** [ddvk/remarkable2-recovery#25]
Hey, guys. My rM 2 is always stuck at the  starting page and has no response/change when charging or connecting to my computer. So I want to know if this project could repair my device, many thanks.

**Comment by Eeems** [comment]
If your device is still functional, and you just don't have UI and SSH access. Yes it can be used to restore it to a working state. If your device is failing to power on due to a hardware reason, no it's unlikely this will be able to do anything.

**Comment by Lebesge** [comment]
> If your device is still functional, and you just don't have UI and SSH access. Yes it can be used to restore it to a working state. If your device is failing to power on due to a hardware reason, no it's unlikely this will be able to do anything.

What do you mean by "functional" and how to check that? I tend to believe the problem is not of hardware and may be caused by an incorrect manipulation when accessing SSH.

**Comment by Lebesge** [comment]
> > > If your device is still functional, and you just don't have UI and SSH access. Yes it can be used to restore it to a working state. If your device is failing to power on due to a hardware reason, no it's unlikely this will be able to do anything.
> > 
> > What do you mean by "functional" and how to check that? I tend to believe the problem is not of hardware and may be caused by an incorrect manipulation when accessing SSH. It's frozen.
> 
> Does the screen flash at all when hard resetting the device? (Hold down power button for 10 seconds, and then press it for 1-2 seconds to power the device back on)

No flash.

**Comment by Lebesge** [comment]
Maybe it doesn't work for my problem.

**Comment by Eeems** [comment]
Have you tried charging it for 3-4 hours first on a slow charger or computer port?

**Comment by Lebesge** [comment]
> Have you tried charging it for 3-4 hours first on a slow charger or computer port?

Yes. I tried it by nothing happened. Thanks for your answers.

**Comment by Eeems** [comment]
> > Have you tried charging it for 3-4 hours first on a slow charger or computer port?
> 
> Yes. I tried it by nothing happened. Thanks for your answers.

Does your computer recognize that a device is connected?

**Comment by Lebesge** [comment]
> > > Have you tried charging it for 3-4 hours first on a slow charger or computer port?
> > 
> > Yes. I tried it by nothing happened. Thanks for your answers.
> 
> Does your computer recognize that a device is connected?

No. When I connect it to my computer, my computer has no tone and I can't access it via SSH.

**Comment by Eeems** [comment]
> > > > Have you tried charging it for 3-4 hours first on a slow charger or computer port?
> > > 
> > > Yes. I tried it by nothing happened. Thanks for your answers.
> > 
> > Does your computer recognize that a device is connected?
> 
> No. When I connect it to my computer, my computer has no tone and I can't access it via SSH.

It does sound like you will be unable to use this to recover your device.

**Comment by Lebesge** [comment]
OK, thanks.
