### ISSUE TITLE
./imx_usb command Does not find RM2

### ISSUE THREAD

**Issue by Xelmarik** [ddvk/remarkable2-recovery#37]
Hello,

I've followed the guide and everyhting has worked up until step  `sudo ./imx_usb`.

Before this, under `dmesg` I get

`[ 1018.549184] hid-generic 0003:15A2:0076.0007: hiddev97,hidraw0: USB HID v1.10 Device [Freescale SemiConductor Inc  SE Blank ULT1] on usb-0000:00:1d.7-1.2/input0`

But `sudo ./imx_usb` returns

```
config file <.//imx_usb.conf>
vid=0x15a2 pid=0x0076 file_name=mx7_usb_work.conf
config file <.//mx7_usb_work.conf>
parse .//mx7_usb_work.conf
Trying to open device vid=0x15a2 pid=0x0076.........................
Could not open device vid=0x15a2 pid=0x0076
[xelmarik@flashendeavor remarkable2-recovery-main]$ ./imx_usb
config file <.//imx_usb.conf>
vid=0x15a2 pid=0x0076 file_name=mx7_usb_work.conf
no matching USB device found
[xelmarik@flashendeavor remarkable2-recovery-main]$ sudo ./imx_usb
[sudo] password for xelmarik: 
config file <.//imx_usb.conf>
vid=0x15a2 pid=0x0076 file_name=mx7_usb_work.conf
no matching USB device found
```

Can you help me understand why this is? I've flipped the break out board, the device restarts and appears in `dmesg -w`.

I'm not sure if I need to modify something in the config file or if there's some other issue.

Thank you.

**Comment by Eeems** [comment]
It looks like you tried multiple times, and it failed to open the first time, you tried running it without sudo a second time, and the third time it didn't find the device. My guess is that you waited long enough that the device rebooted out of upload mode and back into a normal boot.

**Comment by Xelmarik** [comment]
That was it. Thank you.

**Comment by Xelmarik** [comment]
That was it. Thank you.
