### ISSUE TITLE
What are the different partitions?

### ISSUE THREAD

**Issue by triclops200** [ddvk/remarkable2-recovery#6]
I, being a dummy, was playing around with my remarkable 2 without writing down the root password. I bricked it by installing draft. Is rootB a backup factory partition (ie, can I do dd if=\<rootB\> of=\<rootA\>) that I can use to unbrick, or am I going to have to find another way to do it?

**Comment by Eeems** [comment]
You should be able to do that, that said it should be even simpler to just switch to rootB and then let the update process populate rootA for you. You can check if rootB has contents by booting to recovery and mounting it to `/mnt`.

That said, if you've forgotten your password, just enter recovery mode mount the data partition and look at the contents of `.config/remarkable/xochitl.conf`

**Comment by triclops200** [comment]
Thanks!
